init_parallel – QuickPIC
init_parallel Subroutine
8 statements
Source File
private subroutine init_parallel(this)
Arguments
Type Intent Optional Attributes Name
class(parallel), intent(inout) :: this
Calls
Contents
None
Call graph
init_parallel calls init_omp, ppinit2
init_omp calls omp_set_num_threads, omp_get_thread_num, omp_get_max_threads, omp_get_num_procs
ppinit2 calls mpi_initialized, mpi_comm_rank, mpi_comm_size, mpi_init