init_parallel_pipe – QuickPIC
init_parallel_pipe Subroutine
29 statements
Source File
private subroutine init_parallel_pipe(this, nst)
Arguments
Type Intent Optional Attributes Name
class(parallel_pipe), intent(inout) :: this
integer, intent(in) :: nst
Calls
Contents
None
Call graph
init_parallel_pipe calls mpi_comm_size, mpi_comm_split, mpi_comm_rank