init_part2d – QuickPIC
init_part2d Subroutine
58 statements
Source File
private subroutine init_part2d(this, pp, perr, psp, pf, fd, qm, qbm, dt, ci, xdim, npmax, nbmax)
Arguments
Type Intent Optional Attributes Name
class(part2d), intent(inout) :: this
class(parallel_pipe), intent(in), pointer :: pp
class(perrors), intent(in), pointer :: perr
class(spect2d), intent(in), pointer :: psp
class(fdist2d), intent(in) :: pf
class(ufield2d), intent(in), target :: fd
real, intent(in) :: qm
real, intent(in) :: qbm
real, intent(in) :: dt
real, intent(in) :: ci
integer, intent(in) :: xdim
integer, intent(in) :: npmax
integer, intent(in) :: nbmax
Calls
Contents
None
Call graph
init_part2d calls init_prof1, pppmovin2l, ppdblkp2l