ntag – QuickPIC
ntag Function
7 statements
Source File
function ntag()
Arguments
None
Return Value integer
Called by
Contents
None
Call graph
quickpic calls ntag, diagnostic
diagnostic calls ntag