PMOVE32 – QuickPIC
PMOVE32 Subroutine
2010 statements
Source File
subroutine PMOVE32(part, edges, npp, sbufr, sbufl, rbufr, rbufl, ihole, pb uff, jsr, jsl, jss, ny, nz, kstrt, nvpy, nvpz, idimp, npmax, mblok, nblok, idps, nbmax, idds, ntmax, tag1, tag2, id, info)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Arguments
Type Intent Optional Attributes Name
real :: part
real :: edges
integer :: npp
real :: sbufr
real :: sbufl
real :: rbufr
real :: rbufl
integer :: ihole
real :: pb uff
integer :: jsr
integer :: jsl
integer :: jss
integer :: ny
integer :: nz
integer :: kstrt
integer :: nvpy
integer :: nvpz
integer :: idimp
integer :: npmax
integer :: mblok
integer :: nblok
integer :: idps
integer :: nbmax
integer :: idds
integer :: ntmax
integer :: tag1
integer :: tag2
integer :: id
integer :: info
Calls
Contents
Common Blocks
mpi_fortran_bottom mpi_fortran_in_place mpi_fortran_argv_null mpi_fortran_argvs_null mpi_fortran_errcodes_ignore mpi_fortran_status_ignore mpi_fortran_statuses_ignore mpi_fortran_unweighted mpi_fortran_weights_empty PPARMS
Common Blocks
common /mpi_fortran_bottom/
Type Attributes Name Initial
integer :: MPI_BOTTOM
common /mpi_fortran_in_place/
Type Attributes Name Initial
integer :: MPI_IN_PLACE
common /mpi_fortran_argv_null/
Type Attributes Name Initial
integer :: MPI_ARGV_NULL
common /mpi_fortran_argvs_null/
Type Attributes Name Initial
integer :: MPI_ARGVS_NULL
common /mpi_fortran_errcodes_ignore/
Type Attributes Name Initial
integer :: MPI_ERRCODES_IGNORE
common /mpi_fortran_status_ignore/
Type Attributes Name Initial
integer :: MPI_STATUS_IGNORE
common /mpi_fortran_statuses_ignore/
Type Attributes Name Initial
integer :: MPI_STATUSES_IGNORE
common /mpi_fortran_unweighted/
Type Attributes Name Initial
integer :: MPI_UNWEIGHTED
common /mpi_fortran_weights_empty/
Type Attributes Name Initial
integer :: MPI_WEIGHTS_EMPTY
common /PPARMS/
Type Attributes Name Initial
integer :: nproc
integer :: lgrp
integer :: mreal
integer :: mint
integer :: mcplx
integer :: mdouble
integer :: lworld
Call graph
pmove32 calls mpi_get_count, float, mpi_allreduce