PPNCGUARD2L – QuickPIC
PPNCGUARD2L Subroutine
29 statements
Source File
public subroutine PPNCGUARD2L(f, nyp, kstrt, nvp, nxv, nypmx, lgrp, mreal)
Arguments
Type Intent Optional Attributes Name
real, intent(inout), dimension(nxv,nypmx) :: f
integer, intent(in) :: nyp
integer, intent(in) :: kstrt
integer, intent(in) :: nvp
integer, intent(in) :: nxv
integer, intent(in) :: nypmx
integer, intent(in) :: lgrp
integer, intent(in) :: mreal
Calls
Called by
Contents
None
Call graph
ppncguard2l calls mpi_wait, mpi_send
copyguard calls ppncguard2l