PPRNTPOSE – QuickPIC
PPRNTPOSE Subroutine
60 statements
Source File
public subroutine PPRNTPOSE(f, g, s, t, nx, ny, kxp, kyp, kstrt, nvp, ndim, nxv, nyv, kxpd, kypd)
Arguments
Type Intent Optional Attributes Name
real, intent(in), dimension(ndim,nxv,kypd) :: f
real, intent(inout), dimension(ndim,nyv,kxpd) :: g
real, intent(inout), dimension(ndim,(kxp+1)*(kyp+1)) :: s
real, intent(inout), dimension(ndim,(kxp+1)*(kyp+1)) :: t
integer, intent(in) :: nx
integer, intent(in) :: ny
integer, intent(in) :: kxp
integer, intent(in) :: kyp
integer, intent(in) :: kstrt
integer, intent(in) :: nvp
integer, intent(in) :: ndim
integer, intent(in) :: nxv
integer, intent(in) :: nyv
integer, intent(in) :: kxpd
integer, intent(in) :: kypd
Calls
Contents
None
Call graph
pprntpose calls mpi_wait, mpi_irecv, mpi_send