PPRNTPOSE – QuickPIC
PPRNTPOSE Subroutine
10 statements
Source File
subroutine PPRNTPOSE(f, g, s, t, nx, ny, kxp, kyp, kstrt, nvp, ndim, nxv, nyv, kxpd, kypd)
Uses
fft2d_lib
Arguments
Type Intent Optional Attributes Name
real, intent(in), dimension(ndim,nxv,kypd) :: f
real, intent(inout), dimension(ndim,nyv,kxpd) :: g
real, intent(inout), dimension(ndim,kxp*kyp) :: s
real, intent(inout), dimension(ndim,kxp*kyp) :: t
integer, intent(in) :: nx
integer, intent(in) :: ny
integer, intent(in) :: kxp
integer, intent(in) :: kyp
integer, intent(in) :: kstrt
integer, intent(in) :: nvp
integer, intent(in) :: ndim
integer, intent(in) :: nxv
integer, intent(in) :: nyv
integer, intent(in) :: kxpd
integer, intent(in) :: kypd
Calls
Called by
Contents
None
Call graph
pprntpose calls sub
wppfcst2rm2 calls pprntpose
wppfsct2rm3 calls pprntpose
wppfsct2rm22 calls pprntpose
wppfsst2rm23 calls pprntpose
wppfsct2rm2 calls pprntpose
wppfcst2rm3 calls pprntpose
wppfsct2rm4 calls pprntpose