PPRTPOSE – QuickPIC
PPRTPOSE Subroutine
10 statements
Source File
subroutine PPRTPOSE(f, g, s, t, nx, ny, kxp, kyp, kstrt, nvp, nxv, nyv, kxpd, kypd)
Uses
fft2d_lib
Arguments
Type Intent Optional Attributes Name
real, intent(in), dimension(nxv,kypd) :: f
real, intent(inout), dimension(nyv,kxpd) :: g
real, intent(inout), dimension((kxp+1)*(kyp+1)) :: s
real, intent(inout), dimension((kxp+1)*(kyp+1)) :: t
integer, intent(in) :: nx
integer, intent(in) :: ny
integer, intent(in) :: kxp
integer, intent(in) :: kyp
integer, intent(in) :: kstrt
integer, intent(in) :: nvp
integer, intent(in) :: nxv
integer, intent(in) :: nyv
integer, intent(in) :: kxpd
integer, intent(in) :: kypd
Calls
Called by
Contents
None
Call graph
pprtpose calls sub
wppfsct2rm calls pprtpose
wppfcst2rm calls pprtpose
wppfsst2rm calls pprtpose
wppfcct2rm calls pprtpose