PR3TPOSE – QuickPIC
PR3TPOSE Subroutine
66 statements
Source File
subroutine PR3TPOSE(f, g, s, t, nx, ny, kstrt, nxv, nyv, kxp, kyp, kxpd, kypd, jblok, kblok)
Arguments
Type Intent Optional Attributes Name
real :: f
real :: g
real :: s
real :: t
integer :: nx
integer :: ny
integer :: kstrt
integer :: nxv
integer :: nyv
integer :: kxp
integer :: kyp
integer :: kxpd
integer :: kypd
integer :: jblok
integer :: kblok
Calls
Called by
Contents
Common Blocks
PPARMS
Common Blocks
common /PPARMS/
Type Attributes Name Initial
integer :: nproc
integer :: lgrp
integer :: mreal
integer :: mint
integer :: mcplx
integer :: mdouble
integer :: lworld
Call graph
pr3tpose calls mpi_wait
wpfsct2r3 calls pr3tpose
wpfs3t2r3 calls pr3tpose
wpfcst2r3 calls pr3tpose