PRTPOSE – QuickPIC
PRTPOSE Subroutine
62 statements
Source File
subroutine PRTPOSE(f, g, s, t, nx, ny, kstrt, nxv, nyv, kxp, kyp, kxpd, kypd, j blok, kblok)
Arguments
Type Intent Optional Attributes Name
real :: f
real :: g
real :: s
real :: t
integer :: nx
integer :: ny
integer :: kstrt
integer :: nxv
integer :: nyv
integer :: kxp
integer :: kyp
integer :: kxpd
integer :: kypd
integer :: j blok
integer :: kblok
Calls
Called by
Contents
Common Blocks
PPARMS
Common Blocks
common /PPARMS/
Type Attributes Name Initial
integer :: nproc
integer :: lgrp
integer :: mreal
integer :: mint
integer :: mcplx
integer :: mdouble
integer :: lworld
Call graph
prtpose calls mpi_wait
wpfsst2r calls prtpose
wpfcct2r calls prtpose