PWRITE2 – QuickPIC
PWRITE2 Subroutine
45 statements
Source File
subroutine PWRITE2(f, nx, kyp, nxv, kypmx, nblok, iunit, nrec, lrec, name)
Arguments
Type Intent Optional Attributes Name
real :: f
integer :: nx
integer :: kyp
integer :: nxv
integer :: kypmx
integer :: nblok
integer :: iunit
integer :: nrec
integer :: lrec
character(len=*) :: name
Calls
Contents
Common Blocks
PPARMS
Common Blocks
common /PPARMS/
Type Attributes Name Initial
integer :: nproc
integer :: lgrp
integer :: mreal
integer :: mint
integer :: mcplx
integer :: mdouble
integer :: lworld
Call graph
pwrite2 calls mpi_comm_size, mpi_recv, mpi_send, mpi_comm_rank