PWTIMERA – QuickPIC
PWTIMERA Subroutine
17 statements
Source File
subroutine PWTIMERA(icntrl, time, dtime)
Arguments
Type Intent Optional Attributes Name
integer :: icntrl
real :: time
double precision :: dtime
Calls
Called by
Contents
None
Call graph
pwtimera calls mpi_wtime
wppfsct2rm calls pwtimera
wppfcst2rm calls pwtimera
wppfcst2rm2 calls pwtimera
wppfcst2rm3 calls pwtimera
wpfcst2r3 calls pwtimera
wppfsct2rm2 calls pwtimera
wpfcst2r2 calls pwtimera
wpfsct2r2 calls pwtimera
wpfcct2r calls pwtimera
wpfsct2r3 calls pwtimera
wppfsct2rm4 calls pwtimera
wppfsst2rm23 calls pwtimera
wpfs3t2r3 calls pwtimera
wpfsst2r calls pwtimera
wppfcct2rm calls pwtimera
wppfsct2rm3 calls pwtimera
wppfsst2rm calls pwtimera
wppfsct2rm22 calls pwtimera