readrst_part3d – QuickPIC
readrst_part3d Subroutine
10 statements
Source File
private subroutine readrst_part3d(this, file)
Arguments
Type Intent Optional Attributes Name
class(part3d), intent(inout) :: this
class(hdf5file), intent(in) :: file
Calls
Contents
None
Call graph
readrst_part3d calls rpart
rpart calls h5dopen_f, h5aclose_f, h5dread_f, h5screate_simple_f, h5gclose_f, h5gopen_f, h5open_f, detect_precision, h5sclose_f, h5fopen_f, h5aopen_f, h5close_f, h5aread_f, h5fclose_f, h5dclose_f