rpart – QuickPIC
rpart Subroutine
48 statements
Source File
public subroutine rpart(pp, perr, file, part, npp, ierr)
Arguments
Type Intent Optional Attributes Name
class(parallel_pipe), intent(in), pointer :: pp
class(perrors), intent(in), pointer :: perr
class(hdf5file), intent(in) :: file
real, intent(inout), dimension(:,:) :: part
integer, intent(out) :: npp
integer, intent(inout) :: ierr
Calls
Called by
Contents
None
Call graph
rpart calls h5screate_simple_f, h5gclose_f, h5gopen_f, h5dopen_f, h5fclose_f, h5aopen_f, h5sclose_f, h5open_f, h5fopen_f, h5aread_f, h5dclose_f, h5dread_f, detect_precision, h5close_f, h5aclose_f
readrst_part3d calls rpart