wpart – QuickPIC
wpart Subroutine
47 statements
Source File
public subroutine wpart(pp, perr, file, part, npp, dspl, ierr)
Arguments
Type Intent Optional Attributes Name
class(parallel_pipe), intent(in), pointer :: pp
class(perrors), intent(in), pointer :: perr
class(hdf5file), intent(in) :: file
real, intent(in), dimension(:,:) :: part
integer, intent(in) :: npp
integer, intent(in) :: dspl
integer, intent(inout) :: ierr
Calls
Called by
Contents
None
Call graph
wpart calls h5aclose_f, h5screate_simple_f, h5gclose_f, h5gopen_f, h5acreate_f, h5dcreate_f, h5open_f, detect_precision, h5sclose_f, wrattr_dataset, h5fcreate_f, h5close_f, h5awrite_f, h5fclose_f, h5dclose_f, wrattr_file
wrattr_dataset calls add_h5_atribute
wrattr_file calls h5screate_simple_f, h5gclose_f, h5gopen_f, detect_precision, h5sclose_f, h5dclose_f, h5dwrite_f, h5gcreate_f, add_h5_atribute
add_h5_atribute calls add_h5_atribute_int, add_h5_atribute_str, add_h5_atribute_single, add_h5_atribute_v1_single, add_h5_atribute_v1_int, add_h5_atribute_str_v1
add_h5_atribute_int calls h5aclose_f, h5screate_simple_f, h5acreate_f, h5sclose_f, h5awrite_f
add_h5_atribute_str calls h5aclose_f, h5screate_simple_f, h5acreate_f, h5sclose_f, h5awrite_f, h5tset_size_f, h5tcopy_f, h5tclose_f
add_h5_atribute_single calls h5aclose_f, h5screate_simple_f, h5acreate_f, detect_precision, h5sclose_f, h5awrite_f
add_h5_atribute_v1_single calls h5aclose_f, h5screate_simple_f, h5acreate_f, detect_precision, h5sclose_f, h5awrite_f
add_h5_atribute_v1_int calls h5aclose_f, h5screate_simple_f, h5acreate_f, h5sclose_f, h5awrite_f
add_h5_atribute_str_v1 calls h5aclose_f, h5screate_simple_f, h5acreate_f, h5sclose_f, h5awrite_f, h5tset_size_f, h5tcopy_f, h5tclose_f
writerst_part3d calls wpart