WPFS3T2R3 – QuickPIC
WPFS3T2R3 Subroutine
41 statements
Source File
subroutine WPFS3T2R3(f, g, bs, br, isign, ntpose, mixup, sctd, ttp, indx, in dy, kstrt, nxvh, nyv, kxp2, kyp, kypd, kxp2d, jblok, kblok, nxhyd, nxyd)
Arguments
Type Intent Optional Attributes Name
real :: f
real :: g
real :: bs
real :: br
integer :: isign
integer :: ntpose
integer :: mixup
complex :: sctd
real :: ttp
integer :: indx
integer :: in dy
integer :: kstrt
integer :: nxvh
integer :: nyv
integer :: kxp2
integer :: kyp
integer :: kypd
integer :: kxp2d
integer :: jblok
integer :: kblok
integer :: nxhyd
integer :: nxyd
Calls
Contents
None
Call graph
wpfs3t2r3 calls pwtimera, pr3tpose, pfssct2r3y, pfssct2r3x
pwtimera calls mpi_wtime
pr3tpose calls mpi_wait
pfssct2r3x calls float