WPFSCT2R3 – QuickPIC
WPFSCT2R3 Subroutine
41 statements
Source File
subroutine WPFSCT2R3(f, g, bs, br, isign, ntpose, mixup, sctd, ttp, indx, in dy, kstrt, nxvh, nyv, kxp2, kyp, kypd, kxp2d, jblok, kblok, nxhyd, nxyd)
Arguments
Type Intent Optional Attributes Name
real :: f
real :: g
real :: bs
real :: br
integer :: isign
integer :: ntpose
integer :: mixup
complex :: sctd
real :: ttp
integer :: indx
integer :: in dy
integer :: kstrt
integer :: nxvh
integer :: nyv
integer :: kxp2
integer :: kyp
integer :: kypd
integer :: kxp2d
integer :: jblok
integer :: kblok
integer :: nxhyd
integer :: nxyd
Calls
Contents
None
Call graph
wpfsct2r3 calls pwtimera, pfscct2r3x, pr3tpose, pfcsct2r3y
pwtimera calls mpi_wtime
pfscct2r3x calls float
pr3tpose calls mpi_wait