WPPFSCT2RM22 – QuickPIC
WPPFSCT2RM22 Subroutine
48 statements
Source File
subroutine WPPFSCT2RM22(f, g, bs, br, isign, ntpose, mixup, sctd, ttp, indx, indy, kstrt, nvp, nxvh, nyv, kxp2, kyp, kypd, kxp2d, nxhyd, nxyd)
Arguments
Type Intent Optional Attributes Name
real :: f
real :: g
real :: bs
real :: br
integer :: isign
integer :: ntpose
integer :: mixup
complex :: sctd
real :: ttp
integer :: indx
integer :: indy
integer :: kstrt
integer :: nvp
integer :: nxvh
integer :: nyv
integer :: kxp2
integer :: kyp
integer :: kypd
integer :: kxp2d
integer :: nxhyd
integer :: nxyd
Calls
Contents
None
Call graph
wppfsct2rm22 calls pwtimera, ppfscsct2rm22y, ppfsccst2rm22x, pprntpose
pwtimera calls mpi_wtime
pprntpose calls sub