wrattr_dataset – QuickPIC
wrattr_dataset Subroutine
16 statements
Source File
private subroutine wrattr_dataset(this, dset_id, unit, name)
Arguments
Type Intent Optional Attributes Name
class(hdf5file), intent(in) :: this
integer(kind=hid_t), intent(in) :: dset_id
character(len=*), intent(in), optional :: unit
character(len=*), intent(in), optional :: name
Calls
Called by
Contents
None
Call graph
wrattr_dataset calls add_h5_atribute
add_h5_atribute calls add_h5_atribute_str, add_h5_atribute_int, add_h5_atribute_v1_int, add_h5_atribute_v1_single, add_h5_atribute_single, add_h5_atribute_str_v1
add_h5_atribute_str calls h5screate_simple_f, h5tset_size_f, h5sclose_f, h5acreate_f, h5awrite_f, h5tcopy_f, h5aclose_f, h5tclose_f
add_h5_atribute_int calls h5screate_simple_f, h5sclose_f, h5acreate_f, h5awrite_f, h5aclose_f
add_h5_atribute_v1_int calls h5screate_simple_f, h5sclose_f, h5acreate_f, h5awrite_f, h5aclose_f
add_h5_atribute_v1_single calls h5screate_simple_f, h5sclose_f, h5acreate_f, h5awrite_f, detect_precision, h5aclose_f
add_h5_atribute_single calls h5screate_simple_f, h5sclose_f, h5acreate_f, h5awrite_f, detect_precision, h5aclose_f
add_h5_atribute_str_v1 calls h5screate_simple_f, h5tset_size_f, h5sclose_f, h5acreate_f, h5awrite_f, h5tcopy_f, h5aclose_f, h5tclose_f
pwfield_2d calls wrattr_dataset
pwpart_3d_pipe calls wrattr_dataset
pwfield_2d_pipe calls wrattr_dataset
wpart calls wrattr_dataset
wfield_2d_pipe calls wrattr_dataset
pwpart_2d calls wrattr_dataset
pwfield_3d calls wrattr_dataset
pwfield_3d_pipe calls wrattr_dataset
pwpart_pipe calls pwpart_3d_pipe
wfield_pipe calls wfield_2d_pipe
pwfield calls pwfield_2d, pwfield_3d
pwpart calls pwpart_2d
pwfield_pipe calls pwfield_2d_pipe, pwfield_3d_pipe
writerst_part3d calls wpart
writehdf5 calls pwfield
writehdf5_2dslice calls wfield_pipe, pwfield_pipe
writehdf5_part3d calls pwpart_pipe
writehdf5_3d calls pwfield_pipe
writehdf5_part2d calls pwpart