wrattr_file – QuickPIC
wrattr_file Subroutine
34 statements
Source File
private subroutine wrattr_file(this, file_id, xferID)
Arguments
Type Intent Optional Attributes Name
class(hdf5file), intent(in) :: this
integer(kind=hid_t), intent(in) :: file_id
integer(kind=hid_t) :: xferID
Calls
Called by
Contents
None
Call graph
wrattr_file calls h5screate_simple_f, h5gclose_f, h5gcreate_f, h5gopen_f, add_h5_atribute, detect_precision, h5sclose_f, h5dwrite_f, h5dclose_f
add_h5_atribute calls add_h5_atribute_int, add_h5_atribute_str, add_h5_atribute_single, add_h5_atribute_v1_single, add_h5_atribute_v1_int, add_h5_atribute_str_v1
add_h5_atribute_int calls h5screate_simple_f, h5sclose_f, h5aclose_f, h5acreate_f, h5awrite_f
add_h5_atribute_str calls h5screate_simple_f, h5sclose_f, h5aclose_f, h5tcopy_f, h5acreate_f, h5awrite_f, h5tset_size_f, h5tclose_f
add_h5_atribute_single calls h5screate_simple_f, detect_precision, h5sclose_f, h5aclose_f, h5acreate_f, h5awrite_f
add_h5_atribute_v1_single calls h5screate_simple_f, detect_precision, h5sclose_f, h5aclose_f, h5acreate_f, h5awrite_f
add_h5_atribute_v1_int calls h5screate_simple_f, h5sclose_f, h5aclose_f, h5acreate_f, h5awrite_f
add_h5_atribute_str_v1 calls h5screate_simple_f, h5sclose_f, h5aclose_f, h5tcopy_f, h5acreate_f, h5awrite_f, h5tset_size_f, h5tclose_f
wpart calls wrattr_file
pwpart_2d calls wrattr_file
pwpart_3d_pipe calls wrattr_file
wfield_2d_pipe calls wrattr_file
pwfield_2d_pipe calls wrattr_file
pwfield_3d_pipe calls wrattr_file
pwfield_3d calls wrattr_file
pwfield_2d calls wrattr_file
pwpart calls pwpart_2d
wfield_pipe calls wfield_2d_pipe
pwpart_pipe calls pwpart_3d_pipe
pwfield calls pwfield_3d, pwfield_2d
writerst_part3d calls wpart
pwfield_pipe calls pwfield_2d_pipe, pwfield_3d_pipe
writehdf5_part3d calls pwpart_pipe
writehdf5 calls pwfield
writehdf5_2dslice calls wfield_pipe, pwfield_pipe
writehdf5_part2d calls pwpart
writehdf5_3d calls pwfield_pipe