writehdf5_2dslice – QuickPIC
writehdf5_2dslice Subroutine
68 statements
Source File
private subroutine writehdf5_2dslice(this, file, dim, slice, spos, rtag, stag, id)
Arguments
Type Intent Optional Attributes Name
class(ufield3d), intent(inout) :: this
class(hdf5file), intent(in) :: file
integer, intent(in) :: dim
integer, intent(in) :: slice
integer, intent(in) :: spos
integer, intent(in) :: rtag
integer, intent(in) :: stag
integer, intent(inout) :: id
Calls
Contents
None
Call graph
writehdf5_2dslice calls wfield_pipe, pwfield_pipe
wfield_pipe calls wfield_2d_pipe
pwfield_pipe calls pwfield_3d_pipe, pwfield_2d_pipe
wfield_2d_pipe calls h5open_f, h5sclose_f, mpi_irecv, h5gopen_f, h5fopen_f, h5fclose_f, mpi_wait, h5dopen_f, h5screate_simple_f, h5dcreate_f, h5aopen_by_name_f, h5fcreate_f, h5aread_f, h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5gclose_f, detect_precision, wrattr_dataset, h5close_f, h5sselect_hyperslab_f, wrattr_file, h5tclose_f, mpi_isend
pwfield_3d_pipe calls h5open_f, h5sclose_f, mpi_irecv, h5gopen_f, h5fopen_f, h5pset_dxpl_mpio_f, h5fclose_f, mpi_wait, h5dopen_f, h5screate_simple_f, h5dcreate_f, h5aopen_by_name_f, h5fcreate_f, h5aread_f, h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5gclose_f, h5pset_fapl_mpio_f, h5pcreate_f, detect_precision, wrattr_dataset, h5close_f, h5sselect_hyperslab_f, wrattr_file, h5pclose_f, h5tclose_f, mpi_isend
pwfield_2d_pipe calls h5open_f, h5sclose_f, mpi_irecv, h5gopen_f, h5fopen_f, h5pset_dxpl_mpio_f, h5fclose_f, mpi_wait, h5dopen_f, h5screate_simple_f, h5dcreate_f, h5aopen_by_name_f, h5fcreate_f, h5aread_f, h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5gclose_f, h5pset_fapl_mpio_f, h5pcreate_f, detect_precision, wrattr_dataset, h5close_f, h5sselect_hyperslab_f, wrattr_file, h5pclose_f, h5tclose_f, mpi_isend
wrattr_dataset calls add_h5_atribute
wrattr_file calls h5sclose_f, h5gopen_f, h5screate_simple_f, h5dclose_f, h5gclose_f, detect_precision, h5dwrite_f, h5gcreate_f, add_h5_atribute
add_h5_atribute calls add_h5_atribute_int, add_h5_atribute_str, add_h5_atribute_single, add_h5_atribute_v1_single, add_h5_atribute_v1_int, add_h5_atribute_str_v1
add_h5_atribute_int calls h5sclose_f, h5screate_simple_f, h5aclose_f, h5awrite_f, h5acreate_f
add_h5_atribute_str calls h5sclose_f, h5screate_simple_f, h5tset_size_f, h5aclose_f, h5tcopy_f, h5tclose_f, h5awrite_f, h5acreate_f
add_h5_atribute_single calls h5sclose_f, h5screate_simple_f, h5aclose_f, detect_precision, h5awrite_f, h5acreate_f
add_h5_atribute_v1_single calls h5sclose_f, h5screate_simple_f, h5aclose_f, detect_precision, h5awrite_f, h5acreate_f
add_h5_atribute_v1_int calls h5sclose_f, h5screate_simple_f, h5aclose_f, h5awrite_f, h5acreate_f
add_h5_atribute_str_v1 calls h5sclose_f, h5screate_simple_f, h5tset_size_f, h5aclose_f, h5tcopy_f, h5tclose_f, h5awrite_f, h5acreate_f