add_h5_atribute – QuickPIC
add_h5_atribute Interface
8 statements
Source File
private interface add_h5_atribute
Calls
Called by
Contents
Module Procedures
add_h5_atribute_str add_h5_atribute_str_v1 add_h5_atribute_single add_h5_atribute_v1_single add_h5_atribute_int add_h5_atribute_v1_int
Module Procedures
private subroutine add_h5_atribute_str(objID, name, attribute)
Arguments
Type Intent Optional Attributes Name
integer(kind=hid_t), intent(in) :: objID
character(len=*), intent(in) :: name
character(len=*), intent(in) :: attribute
private subroutine add_h5_atribute_str_v1(objID, name, attribute)
Arguments
Type Intent Optional Attributes Name
integer(kind=hid_t), intent(in) :: objID
character(len=*), intent(in) :: name
character(len=*), intent(in), dimension(:) :: attribute
private subroutine add_h5_atribute_single(objID, name, attribute)
Arguments
Type Intent Optional Attributes Name
integer(kind=hid_t), intent(in) :: objID
character(len=*), intent(in) :: name
real, intent(in) :: attribute
private subroutine add_h5_atribute_v1_single(objID, name, attribute)
Arguments
Type Intent Optional Attributes Name
integer(kind=hid_t), intent(in) :: objID
character(len=*), intent(in) :: name
real, intent(in), dimension(:) :: attribute
private subroutine add_h5_atribute_int(objID, name, attribute)
Arguments
Type Intent Optional Attributes Name
integer(kind=hid_t), intent(in) :: objID
character(len=*), intent(in) :: name
integer, intent(in) :: attribute
private subroutine add_h5_atribute_v1_int(objID, name, attribute)
Arguments
Type Intent Optional Attributes Name
integer(kind=hid_t), intent(in) :: objID
character(len=*), intent(in) :: name
integer, intent(in), dimension(:) :: attribute
Call graph
add_h5_atribute calls add_h5_atribute_str, add_h5_atribute_int, add_h5_atribute_v1_int, add_h5_atribute_v1_single, add_h5_atribute_single, add_h5_atribute_str_v1
add_h5_atribute_str calls h5screate_simple_f, h5tset_size_f, h5sclose_f, h5acreate_f, h5awrite_f, h5tcopy_f, h5aclose_f, h5tclose_f
add_h5_atribute_int calls h5screate_simple_f, h5sclose_f, h5acreate_f, h5awrite_f, h5aclose_f
add_h5_atribute_v1_int calls h5screate_simple_f, h5sclose_f, h5acreate_f, h5awrite_f, h5aclose_f
add_h5_atribute_v1_single calls h5screate_simple_f, h5sclose_f, h5acreate_f, h5awrite_f, detect_precision, h5aclose_f
add_h5_atribute_single calls h5screate_simple_f, h5sclose_f, h5acreate_f, h5awrite_f, detect_precision, h5aclose_f
add_h5_atribute_str_v1 calls h5screate_simple_f, h5tset_size_f, h5sclose_f, h5acreate_f, h5awrite_f, h5tcopy_f, h5aclose_f, h5tclose_f
wrattr_dataset calls add_h5_atribute
wrattr_file calls add_h5_atribute
pwfield_2d calls wrattr_dataset, wrattr_file
pwpart_3d_pipe calls wrattr_dataset, wrattr_file
pwfield_2d_pipe calls wrattr_dataset, wrattr_file
wpart calls wrattr_dataset, wrattr_file
wfield_2d_pipe calls wrattr_dataset, wrattr_file
pwpart_2d calls wrattr_dataset, wrattr_file
pwfield_3d calls wrattr_dataset, wrattr_file
pwfield_3d_pipe calls wrattr_dataset, wrattr_file
pwpart_pipe calls pwpart_3d_pipe
wfield_pipe calls wfield_2d_pipe
pwfield calls pwfield_2d, pwfield_3d
pwpart calls pwpart_2d
pwfield_pipe calls pwfield_2d_pipe, pwfield_3d_pipe
writerst_part3d calls wpart
writehdf5 calls pwfield
writehdf5_2dslice calls wfield_pipe, pwfield_pipe
writehdf5_part3d calls pwpart_pipe
writehdf5_3d calls pwfield_pipe
writehdf5_part2d calls pwpart