PPPMOVIN2L – QuickPIC
PPPMOVIN2L Interface
11 statements
Source File
interface
Called by
public subroutine PPPMOVIN2L(part, ppart, kpic, npp, noff, nppmx, idimp, npmax, mx, my, mx1, mxyp1, irc)
Arguments
Type Intent Optional Attributes Name
real, intent(in), dimension(idimp,npmax) :: part
real, intent(inout), dimension(idimp,nppmx,mxyp1) :: ppart
integer, intent(inout), dimension(mxyp1) :: kpic
integer, intent(in) :: npp
integer, intent(in) :: noff
integer, intent(in) :: nppmx
integer, intent(in) :: idimp
integer, intent(in) :: npmax
integer, intent(in) :: mx
integer, intent(in) :: my
integer, intent(in) :: mx1
integer, intent(in) :: mxyp1
integer, intent(inout) :: irc
Call graph
init_part2d calls pppmovin2l
renew_part2d calls pppmovin2l
partcopy calls pppmovin2l