pwfield – QuickPIC
pwfield Interface
4 statements
Source File
public interface pwfield
Calls
Called by
Contents
Module Procedures
pwfield_3d pwfield_2d
Module Procedures
private subroutine pwfield_3d(pp, perr, file, fd, gs, ls, noff, ierr)
Arguments
Type Intent Optional Attributes Name
class(parallel_pipe), intent(in), pointer :: pp
class(perrors), intent(in), pointer :: perr
class(hdf5file), intent(in) :: file
real, intent(in), dimension(:,:,:) :: fd
integer, intent(in), dimension(3) :: gs
integer, intent(in), dimension(3) :: ls
integer, intent(in), dimension(2) :: noff
integer, intent(inout) :: ierr
private subroutine pwfield_2d(pp, perr, file, fd, gs, ls, noff, ierr)
Arguments
Type Intent Optional Attributes Name
class(parallel_pipe), intent(in), pointer :: pp
class(perrors), intent(in), pointer :: perr
class(hdf5file), intent(in) :: file
real, intent(in), dimension(:,:) :: fd
integer, intent(in), dimension(2) :: gs
integer, intent(in), dimension(2) :: ls
integer, intent(in) :: noff
integer, intent(inout) :: ierr
Call graph
pwfield calls pwfield_3d, pwfield_2d
pwfield_3d calls h5screate_simple_f, h5gclose_f, h5pset_fapl_mpio_f, h5gopen_f, h5pcreate_f, h5dcreate_f, h5open_f, detect_precision, h5sclose_f, h5pset_dxpl_mpio_f, wrattr_dataset, h5fcreate_f, h5close_f, h5sselect_hyperslab_f, h5fclose_f, h5dclose_f, wrattr_file, h5pclose_f
pwfield_2d calls h5screate_simple_f, h5gclose_f, h5pset_fapl_mpio_f, h5gopen_f, h5pcreate_f, h5dcreate_f, h5open_f, detect_precision, h5sclose_f, h5pset_dxpl_mpio_f, wrattr_dataset, h5fcreate_f, h5close_f, h5sselect_hyperslab_f, h5fclose_f, h5dclose_f, wrattr_file, h5pclose_f
wrattr_dataset calls add_h5_atribute
wrattr_file calls h5screate_simple_f, h5gclose_f, h5gopen_f, detect_precision, h5sclose_f, h5dclose_f, h5dwrite_f, h5gcreate_f, add_h5_atribute
add_h5_atribute calls add_h5_atribute_int, add_h5_atribute_str, add_h5_atribute_single, add_h5_atribute_v1_single, add_h5_atribute_v1_int, add_h5_atribute_str_v1
add_h5_atribute_int calls h5screate_simple_f, h5sclose_f, h5aclose_f, h5acreate_f, h5awrite_f
add_h5_atribute_str calls h5screate_simple_f, h5sclose_f, h5aclose_f, h5tcopy_f, h5acreate_f, h5awrite_f, h5tset_size_f, h5tclose_f
add_h5_atribute_single calls h5screate_simple_f, detect_precision, h5sclose_f, h5aclose_f, h5acreate_f, h5awrite_f
add_h5_atribute_v1_single calls h5screate_simple_f, detect_precision, h5sclose_f, h5aclose_f, h5acreate_f, h5awrite_f
add_h5_atribute_v1_int calls h5screate_simple_f, h5sclose_f, h5aclose_f, h5acreate_f, h5awrite_f
add_h5_atribute_str_v1 calls h5screate_simple_f, h5sclose_f, h5aclose_f, h5tcopy_f, h5acreate_f, h5awrite_f, h5tset_size_f, h5tclose_f
writehdf5 calls pwfield