pwfield_pipe – QuickPIC
pwfield_pipe Interface
4 statements
Source File
public interface pwfield_pipe
Calls
Called by
Contents
Module Procedures
pwfield_3d_pipe pwfield_2d_pipe
Module Procedures
private subroutine pwfield_3d_pipe(pp, perr, file, fd, gs, ls, noff, rtag, stag, id, ierr)
Arguments
Type Intent Optional Attributes Name
class(parallel_pipe), intent(in), pointer :: pp
class(perrors), intent(in), pointer :: perr
class(hdf5file), intent(in) :: file
real, intent(in), dimension(:,:,:) :: fd
integer, intent(in), dimension(3) :: gs
integer, intent(in), dimension(3) :: ls
integer, intent(in), dimension(2) :: noff
integer, intent(in) :: rtag
integer, intent(in) :: stag
integer, intent(inout) :: id
integer, intent(inout) :: ierr
private subroutine pwfield_2d_pipe(pp, perr, file, fd, gs, ls, noff, rtag, stag, id, ierr)
Arguments
Type Intent Optional Attributes Name
class(parallel_pipe), intent(in), pointer :: pp
class(perrors), intent(in), pointer :: perr
class(hdf5file), intent(in) :: file
real, intent(in), dimension(:,:) :: fd
integer, intent(in), dimension(2) :: gs
integer, intent(in), dimension(2) :: ls
integer, intent(in), dimension(2) :: noff
integer, intent(in) :: rtag
integer, intent(in) :: stag
integer, intent(inout) :: id
integer, intent(inout) :: ierr
Call graph
pwfield_pipe calls pwfield_3d_pipe, pwfield_2d_pipe
pwfield_3d_pipe calls h5open_f, h5sclose_f, mpi_irecv, h5gopen_f, h5pset_dxpl_mpio_f, h5fopen_f, h5fclose_f, mpi_wait, h5dopen_f, h5screate_simple_f, h5dcreate_f, h5aopen_by_name_f, h5fcreate_f, h5aread_f, h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5gclose_f, h5pset_fapl_mpio_f, h5pcreate_f, detect_precision, wrattr_dataset, h5close_f, h5sselect_hyperslab_f, wrattr_file, h5pclose_f, h5tclose_f, mpi_isend
pwfield_2d_pipe calls h5open_f, h5sclose_f, mpi_irecv, h5gopen_f, h5pset_dxpl_mpio_f, h5fopen_f, h5fclose_f, mpi_wait, h5dopen_f, h5screate_simple_f, h5dcreate_f, h5aopen_by_name_f, h5fcreate_f, h5aread_f, h5tset_size_f, h5dclose_f, h5aclose_f, h5tcopy_f, h5gclose_f, h5pset_fapl_mpio_f, h5pcreate_f, detect_precision, wrattr_dataset, h5close_f, h5sselect_hyperslab_f, wrattr_file, h5pclose_f, h5tclose_f, mpi_isend
wrattr_dataset calls add_h5_atribute
wrattr_file calls h5sclose_f, h5gopen_f, h5screate_simple_f, h5dclose_f, h5gclose_f, detect_precision, h5dwrite_f, h5gcreate_f, add_h5_atribute
add_h5_atribute calls add_h5_atribute_int, add_h5_atribute_str, add_h5_atribute_single, add_h5_atribute_v1_single, add_h5_atribute_v1_int, add_h5_atribute_str_v1
add_h5_atribute_int calls h5sclose_f, h5screate_simple_f, h5aclose_f, h5awrite_f, h5acreate_f
add_h5_atribute_str calls h5sclose_f, h5screate_simple_f, h5tset_size_f, h5aclose_f, h5tcopy_f, h5tclose_f, h5awrite_f, h5acreate_f
add_h5_atribute_single calls h5sclose_f, h5screate_simple_f, h5aclose_f, detect_precision, h5awrite_f, h5acreate_f
add_h5_atribute_v1_single calls h5sclose_f, h5screate_simple_f, h5aclose_f, detect_precision, h5awrite_f, h5acreate_f
add_h5_atribute_v1_int calls h5sclose_f, h5screate_simple_f, h5aclose_f, h5awrite_f, h5acreate_f
add_h5_atribute_str_v1 calls h5sclose_f, h5screate_simple_f, h5tset_size_f, h5aclose_f, h5tcopy_f, h5tclose_f, h5awrite_f, h5acreate_f
writehdf5_2dslice calls pwfield_pipe
writehdf5_3d calls pwfield_pipe