pwpart_pipe – QuickPIC
pwpart_pipe Interface
3 statements
Source File
public interface pwpart_pipe
Calls
Called by
Contents
Module Procedures
pwpart_3d_pipe
Module Procedures
private subroutine pwpart_3d_pipe(pp, perr, file, part, npp, dspl, delta, rtag, stag, id, ierr)
Arguments
Type Intent Optional Attributes Name
class(parallel_pipe), intent(in), pointer :: pp
class(perrors), intent(in), pointer :: perr
class(hdf5file), intent(in) :: file
real, intent(in), dimension(:,:) :: part
integer, intent(in) :: npp
integer, intent(in) :: dspl
real, intent(in), dimension(3) :: delta
integer, intent(in) :: rtag
integer, intent(in) :: stag
integer, intent(inout) :: id
integer, intent(inout) :: ierr
Call graph
pwpart_pipe calls pwpart_3d_pipe
pwpart_3d_pipe calls h5gopen_f, wrattr_file, h5aclose_f, h5sclose_f, h5pset_chunk_f, mpi_comm_rank, mpi_isend, h5pset_dxpl_mpio_f, h5screate_simple_f, h5gclose_f, h5open_f, h5pcreate_f, mpi_allreduce, h5acreate_f, wrattr_dataset, h5dcreate_f, mpi_comm_free, mpi_allgather, mpi_irecv, h5aopen_f, h5fclose_f, mpi_comm_split, h5sselect_hyperslab_f, h5dclose_f, h5aread_f, h5close_f, h5pclose_f, h5dextend_f, h5pset_fapl_mpio_f, h5dopen_f, h5fopen_f, h5dwrite_f, h5awrite_f, detect_precision, mpi_comm_size, mpi_wait, h5fcreate_f
wrattr_file calls h5gopen_f, h5sclose_f, h5screate_simple_f, h5gclose_f, h5dclose_f, h5dwrite_f, detect_precision, h5gcreate_f, add_h5_atribute
wrattr_dataset calls add_h5_atribute
add_h5_atribute calls add_h5_atribute_str, add_h5_atribute_int, add_h5_atribute_v1_int, add_h5_atribute_v1_single, add_h5_atribute_single, add_h5_atribute_str_v1
add_h5_atribute_str calls h5aclose_f, h5sclose_f, h5screate_simple_f, h5acreate_f, h5awrite_f, h5tset_size_f, h5tcopy_f, h5tclose_f
add_h5_atribute_int calls h5aclose_f, h5sclose_f, h5screate_simple_f, h5acreate_f, h5awrite_f
add_h5_atribute_v1_int calls h5aclose_f, h5sclose_f, h5screate_simple_f, h5acreate_f, h5awrite_f
add_h5_atribute_v1_single calls h5aclose_f, h5sclose_f, h5screate_simple_f, h5acreate_f, h5awrite_f, detect_precision
add_h5_atribute_single calls h5aclose_f, h5sclose_f, h5screate_simple_f, h5acreate_f, h5awrite_f, detect_precision
add_h5_atribute_str_v1 calls h5aclose_f, h5sclose_f, h5screate_simple_f, h5acreate_f, h5awrite_f, h5tset_size_f, h5tcopy_f, h5tclose_f
writehdf5_part3d calls pwpart_pipe