wfield_pipe – QuickPIC
wfield_pipe Interface
3 statements
Source File
public interface wfield_pipe
Calls
Called by
Contents
Module Procedures
wfield_2d_pipe
Module Procedures
private subroutine wfield_2d_pipe(pp, perr, file, fd, gs, ls, noff, rtag, stag, id, ierr)
Arguments
Type Intent Optional Attributes Name
class(parallel_pipe), intent(in), pointer :: pp
class(perrors), intent(in), pointer :: perr
class(hdf5file), intent(in) :: file
real, intent(in), dimension(:,:) :: fd
integer, intent(in), dimension(2) :: gs
integer, intent(in), dimension(2) :: ls
integer, intent(in), dimension(2) :: noff
integer, intent(in) :: rtag
integer, intent(in) :: stag
integer, intent(inout) :: id
integer, intent(inout) :: ierr
Call graph
wfield_pipe calls wfield_2d_pipe
wfield_2d_pipe calls h5gopen_f, wrattr_file, h5sclose_f, h5tcopy_f, h5aopen_by_name_f, mpi_isend, h5screate_simple_f, h5gclose_f, h5tset_size_f, h5open_f, wrattr_dataset, h5dcreate_f, mpi_irecv, h5tclose_f, h5fclose_f, h5sselect_hyperslab_f, h5dclose_f, h5aread_f, h5close_f, h5dopen_f, h5fopen_f, detect_precision, h5fcreate_f, mpi_wait, h5aclose_f
wrattr_file calls h5gopen_f, h5sclose_f, h5screate_simple_f, h5gclose_f, h5dclose_f, detect_precision, h5dwrite_f, h5gcreate_f, add_h5_atribute
wrattr_dataset calls add_h5_atribute
add_h5_atribute calls add_h5_atribute_str, add_h5_atribute_int, add_h5_atribute_v1_int, add_h5_atribute_v1_single, add_h5_atribute_single, add_h5_atribute_str_v1
add_h5_atribute_str calls h5sclose_f, h5tcopy_f, h5screate_simple_f, h5tset_size_f, h5tclose_f, h5aclose_f, h5acreate_f, h5awrite_f
add_h5_atribute_int calls h5sclose_f, h5screate_simple_f, h5aclose_f, h5acreate_f, h5awrite_f
add_h5_atribute_v1_int calls h5sclose_f, h5screate_simple_f, h5aclose_f, h5acreate_f, h5awrite_f
add_h5_atribute_v1_single calls h5sclose_f, h5screate_simple_f, detect_precision, h5aclose_f, h5acreate_f, h5awrite_f
add_h5_atribute_single calls h5sclose_f, h5screate_simple_f, detect_precision, h5aclose_f, h5acreate_f, h5awrite_f
add_h5_atribute_str_v1 calls h5sclose_f, h5tcopy_f, h5screate_simple_f, h5tset_size_f, h5tclose_f, h5aclose_f, h5acreate_f, h5awrite_f
writehdf5_2dslice calls wfield_pipe