quickpic – QuickPIC
quickpic Program
650 statements
Source File
Uses
parallel_class
parallel_pipe_class
perrors_class
spect3d_class
spect2d_class
field2d_class
fdist2d_class
field3d_class
beam3d_class
species2d_class
fdist3d_class
hdf5io_class
input_class
mpi
Calls
Contents
Variables
sim pp perr psp3 psp2 qb qe qi psit psi div_vpot reg fxy bxyz cu dcu amu epw epwb qe0 cu0 dcu0 amu0 bexyz bbxyz qeb qep psi3d cu3d pf spe pf3 beam file2d file3d filep file_rst ierr iter nstep3d nstep2d start3d id tag tag_spe id_spe id_br tag_beam id_beam id_qep id_qeps istat i j l m n erstr stime dex dxi dex2
Functions
ntag
Subroutines
initialization diagnostic str
Variables
Type Attributes Name Initial
type(input) :: sim
class(parallel_pipe), pointer :: pp => null()
class(perrors), pointer :: perr => null()
class(spect3d), pointer :: psp3 => null()
class(spect2d), pointer :: psp2 => null()
type(field2d) :: qb
type(field2d) :: qe
type(field2d) :: qi
type(field2d) :: psit
type(field2d) :: psi
type(field2d) :: div_vpot
type(field2d) :: reg
type(field2d) :: fxy
type(field2d) :: bxyz
type(field2d) :: cu
type(field2d) :: dcu
type(field2d) :: amu
type(field2d) :: epw
type(field2d) :: epwb
type(field2d), dimension(:), allocatable :: qe0
type(field2d), dimension(:), allocatable :: cu0
type(field2d), dimension(:), allocatable :: dcu0
type(field2d), dimension(:), allocatable :: amu0
type(field3d) :: bexyz
type(field3d) :: bbxyz
type(field3d) :: qeb
type(field3d), dimension(:), allocatable :: qep
type(field3d), allocatable :: psi3d
type(field3d), allocatable :: cu3d
type(fdist2d), dimension(:), allocatable :: pf
type(species2d), dimension(:), allocatable :: spe
type(fdist3d), dimension(:), allocatable :: pf3
type(beam3d), dimension(:), allocatable :: beam
type(hdf5file) :: file2d
type(hdf5file) :: file3d
type(hdf5file) :: filep
type(hdf5file) :: file_rst
integer :: ierr
integer :: iter
integer :: nstep3d
integer :: nstep2d
integer :: start3d
integer, dimension(54) :: id
integer, dimension(8) :: tag
integer, dimension(:), allocatable :: tag_spe
integer, dimension(:), allocatable :: id_spe
integer, dimension(:), allocatable :: id_br
integer, dimension(:), allocatable :: tag_beam
integer, dimension(:), allocatable :: id_beam
integer, dimension(:), allocatable :: id_qep
integer, dimension(:), allocatable :: id_qeps
integer, dimension(10) :: istat
integer :: i
integer :: j
integer :: l
integer :: m
integer :: n
character(len=128) :: erstr
character(len=20) :: stime
real :: dex
real :: dxi
real :: dex2
Functions
function ntag()
Arguments
None
Return Value integer
Subroutines
subroutine initialization()
Arguments
None
subroutine diagnostic()
Arguments
None
subroutine str(int_in, string, ndigits)
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: int_in
character(len=20), intent(inout) :: string
integer, intent(in) :: ndigits
Call graph
quickpic calls mpi_finalize, initialization, diagnostic, ntag
initialization calls str, mpi_barrier
diagnostic calls ntag, str